### ISSUE TITLE
problem with set image grayscale using histogram

### ISSUE THREAD

**Issue by djraymondnm** [dankelley/gri#9] opened 2015-04-25 22:09 UTC
I noticed that `set image grayscale using histogram` doesn't work unless a previous `convert grid to image` has been done. Using the same test_case.nc data file used in the `set image range` issue, the following code

```
open test_case.nc netcdf
set missing value 1.0e30
set x size 10
set y size 10
set x margin 6
set y margin 6
set x axis unknown
set y axis unknown
set x name "lon"
set y name "lat"
set clip on
read grid x = "lon"
read grid y = "lat"
read grid data = "rh"
set image range from grid
set image grayscale using histogram
convert grid to image
draw image
draw axes if needed
```

fails with the message

```
loro:/data/raymond$ gri test_case.gri 
ERROR: no image exists
 Bad command:  `set image grayscale using histogram'
 Error at test_case.gri:16
```

while

```
open test_case.nc netcdf
set missing value 1.0e30
set x size 10
set y size 10
set x margin 6
set y margin 6
set x axis unknown
set y axis unknown
set x name "lon"
set y name "lat"
set clip on
read grid x = "lon"
read grid y = "lat"
read grid data = "rh"
set image range from grid
convert grid to image
set image grayscale using histogram
convert grid to image
draw image
draw axes if needed
```

succeeds with the message

```
loro:/data/raymond$ gri test_case.gri 
`convert grid to image':
  Image is 128 wide and 128 tall, with x in range (143,150) and y in range (11, 18)
`convert grid to image':
  Image is 128 wide and 128 tall, with x in range (143,150) and y in range (11, 18)
```

Sounds like some kind of initialization issue.  `set image grayscale` with specified values works without this hack.

**Comment by dankelley** [comment] 2015-04-26 21:42
The histogram method works by adjusting the grayscale mapping in such a way as to create an image with equal area of each gray level. Therefore, it requires the existence of an image. It is failing because no image exists at the time when ``set image grayscale`` is called.

So the solution for the user is to create the image first.

I don't think Gri should be changed.

In theory, gri could be set up to "remember" to set up the histogram-based grayscale once the image is created, but this is not the convention within gri. Generally, in gri, things work step by step, on existing data/information. Also, there is the question of when to set up the grayscale mapping. Possibly it should be at the time of image creation, but it could get modified later, so that might argue for doing it just before plotting. But there are other things that might be done besides plotting.  I don't think I'm being terribly clear on what I'm saying, and maybe it's not even convincing in this particular case, but this is the sort of thought process that lies underneath the Gri system.

Also, I'm a bit scared about setting up code to "remember" a future intention, because there could be some side effects on existing code. In other words, users might have come to expect an error message under the state we are discussing, and changing from an error to a new feature could make things confusing for users.

So, and this is unusual for me, I'm arguing for "not a bug" as the resolution to this.

@djraymondnm -- what do you think?

@psg -- any comments on this?

**Comment by djraymondnm** [comment] 2015-04-27 23:37
Dan,

What you say makes perfect sense to me.  Is it worth adding a sentence
to the documentation regarding the necessity for a previous image?

Dave

**Comment by dankelley** [comment] 2015-04-29 11:14
Thanks. I clarified the docs.

**Comment by dankelley** [comment] 2019-03-11 09:35
This seems to have been addressed, so I'm closing this.

**Closed by dankelley** 2019-03-11 09:35 UTC
